plugins {
    id 'java'
    id 'eclipse'
    id 'application'
}

application {
    mainClass = 'evaluation.JavaEvaluator'
}

dependencies {
    implementation("io.github.bonede:tree-sitter:0.22.6")
    implementation("io.github.bonede:tree-sitter-javascript:0.23.1")
    implementation("io.github.bonede:tree-sitter-ruby:0.23.1")
    implementation("io.github.bonede:tree-sitter-go:0.23.3")

    implementation project(':refdiff-universal')
    implementation project(':refdiff-java')

    testImplementation 'junit:junit:4.11'
}

task runJavaEvaluation(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    mainClass = 'detection.JavaEvaluator'
}

task runCalculator(type: Exec) {
    group = 'Python Scripts'
    description = 'Runs the CSV processing Python script.'

    workingDir 'calculator'
    commandLine 'sh', '-c', 'venv/bin/python -m src.main'

    standardOutput = System.out
    errorOutput = System.err
}
