plugins {
    id 'java'
    id 'eclipse'
    id 'application'
}

application {
    mainClass = 'kyutech.experiment.ExperimentForKyutech'
}

dependencies {
    implementation project(':refdiff-universal')
    implementation project(':refdiff-java')
}

task runExperiment(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    mainClass = 'kyutech.experiment.ExperimentForKyutech'
}