plugins {
    id 'java-library'
    id 'eclipse'
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':refdiff-core')

    implementation("io.github.bonede:tree-sitter:0.22.6")
    implementation("io.github.bonede:tree-sitter-java:0.21.0a")

}

task run(type: JavaExec) {
    classpath sourceSets.main.runtimeClasspath
    mainClass = 'refdiff.parsers.universal.UniversalParser'
}
