plugins {
  id 'java'
  id 'eclipse'
  id 'application'
}

application {
  mainClass = 'pluginmaker.PluginMaker'
}

dependencies {
  implementation("io.github.bonede:tree-sitter:0.22.6")
  implementation("io.github.bonede:tree-sitter-python:0.23.4")
  
  implementation project(':refdiff-universal')
  implementation project(':refdiff-core')
}